### ISSUE TITLE
doesn't apply to oldest files

### ISSUE THREAD

**Issue by radix** [rocioar/gradual-black-formatter#1]
Heya, this is a really cool action!

However, I'd like to point out that it doesn't seem to apply to the oldest files first. It seems to just apply to the order that `git ls-tree -r HEAD` returns, which seems to be alphabetical.

I believe in order to get the time that a file was most recently modified in git, you'll need to use a command like `git log -1 --format="%ci" $FILENAME`, and then sort the files by that.

**Comment by rocioar** [comment]
Oh wow, what did I miss here? I will get this fixed up ASAP. Thanks for reporting it!

**Comment by rocioar** [comment]
I have fixed this issue on PR: https://github.com/rocioar/gradual-black-formatter/pull/2. And released v2. Thanks for reporting :)

**Comment by radix** [comment]
Thanks @rocioar, I appreciate it!
